# Generated by Django 5.2.7 on 2025-10-27 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='instructor.course')),
            ],
        ),
    ]
