# Generated by Django 5.2.7 on 2025-10-27 09:21

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
                ('order', models.PositiveBigIntegerField()),
                ('module_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='instructor.module')),
            ],
        ),
    ]
